#!/bin/bash
#
# This is a small wrapper script around the standard thinstation functionality.
#
# It should help in generating the respective PXE images we are interested in.
# At the same time it will allow to preserve private information which shouldn't
# be put on the GitHub server where the 
#
# Copyright (c) 2013-2014 Jens Maus <mail@jens-maus.de>
#

TFTP_ROOT="/tftpboot"

# get the version number for our build
if [ -e "VERSION" ]; then
  VERSION=`cat VERSION`
else
  # request the root password
  echo -n "Please enter a version number: "
  read VERSION
  echo ${VERSION} >VERSION
  chmod 660 VERSION
fi

# check for a PASSWD file and if not present request from user
if [ -e "PASSWD" ]; then
  PASSWD=`cat PASSWD`
else
  # request the root password
  echo -n "Please enter a root password: "
  read -s PASSWD
  echo
  echo ${PASSWD} >PASSWD
  chmod 660 PASSWD
fi

# check that we have ssh keys installed
if [ ! -e "ts/build/id_rsa" ]; then
  if [ -e "../id_rsa" ]; then
    sudo cp -a "../id_rsa" "ts/build/"
  else
    echo "ERROR: ts/build/id_rsa SSH keyfile missing"
    exit 2
  fi
fi
if [ ! -e "ts/build/id_rsa.pub" ]; then
  if [ -e "../id_rsa.pub" ]; then
    sudo cp -a "../id_rsa.pub" "ts/build/"
  else
    echo "ERROR: ts/build/id_rsa.pub SSH public keyfile missing"
    exit 2
  fi
fi

# let us copy the build.conf.example file to build.conf.private and
# stuff in the root password into it (build.conf.private will not be
# put on GitHub&co)
sudo sed "s/pleasechangeme/${PASSWD}/g" ts/build/conf/hzdr/build.conf.example >ts/build/conf/hzdr/build.conf.private
sudo chmod 660 ts/build/conf/hzdr/build.conf.private
sudo cp ts/build/conf/hzdr/thinstation.conf.buildtime ts/build/

# run the image build process and use the SMP kernel as well as the private
# build.conf
sudo ./setup-chroot -a -b -o --kernel 64 conf/hzdr/build.conf.private
#sudo ./setup-chroot -b -o --allmodules --kernel 64 conf/hzdr/build.conf.private

# revert changes to buildtime file
sudo git checkout ts/build/thinstation.conf.buildtime

# copy the images to the respective TFTP directory
if [ -e "${TFTP_ROOT}" ]; then
  if [ ! -e "${TFTP_ROOT}/thinstation" ]; then
    mkdir "${TFTP_ROOT}/thinstation"
  fi
  cp ts/build/boot-images/pxe/boot/initrd ${TFTP_ROOT}/thinstation/initrd-${VERSION}
  cp ts/build/boot-images/pxe/boot/lib.squash ${TFTP_ROOT}/thinstation/lib.squash-${VERSION}
  cp ts/build/boot-images/pxe/boot/vmlinuz ${TFTP_ROOT}/thinstation/vmlinuz-${VERSION}
  cp ts/build/boot-images/pkg-packages/*.pkg ${TFTP_ROOT}/thinstation/conf/pkg/
fi
