#!/bin/bash
#
# This is a small wrapper script around the standard thinstation functionality.
#
# It should help in generating the respective PXE images we are interested in.
# At the same time it will allow to preserve private information which shouldn't
# be put on the GitHub server where the 
#
# Copyright (c) 2013 Jens Maus <mail@jens-maus.de>
#

TFTP_ROOT="/tftpboot"
TS_VERSION="5.2"

# get the version number for our build
if [ -e "VERSION" ]; then
  VERSION=`cat VERSION`
else
  # request the root password
  echo -n "Please enter a version number: "
  read VERSION
  echo ${VERSION} >VERSION
  chmod 660 VERSION
fi

# check for a PASSWD file and if not present request from user
if [ -e "PASSWD" ]; then
  PASSWD=`cat PASSWD`
else
  # request the root password
  echo -n "Please enter a root password: "
  read -s PASSWD
  echo
  echo ${PASSWD} >PASSWD
  chmod 660 PASSWD
fi

# check that we have ssh keys installed
if [ ! -e "ts/${TS_VERSION}/id_rsa" ]; then
  if [ -e "../id_rsa" ]; then
    cp -a "../id_rsa" "ts/${TS_VERSION}/"
  else
    echo "ERROR: ts/${TS_VERSION}/id_rsa SSH keyfile missing"
    exit 2
  fi
fi
if [ ! -e "ts/${TS_VERSION}/id_rsa.pub" ]; then
  if [ -e "../id_rsa.pub" ]; then
    cp -a "../id_rsa.pub" "ts/${TS_VERSION}/"
  else
    echo "ERROR: ts/${TS_VERSION}/id_rsa.pub SSH public keyfile missing"
    exit 2
  fi
fi

# let us copy the build.conf.example file to build.conf.private and
# stuff in the root password into it (build.conf.private will not be
# put on GitHub&co)
sed "s/pleasechangeme/${PASSWD}/g" ts/${TS_VERSION}/conf/hzdr/build.conf.example >ts/${TS_VERSION}/conf/hzdr/build.conf.private
chmod 660 ts/${TS_VERSION}/conf/hzdr/build.conf.private
cp ts/${TS_VERSION}/conf/hzdr/thinstation.conf.buildtime ts/${TS_VERSION}/

# run the image build process and use the SMP kernel as well as the private
# build.conf
sudo ./setup-chroot -b -o --kernel SMP conf/hzdr/build.conf.private
#sudo ./setup-chroot -b -o --allmodules --kernel SMP conf/hzdr/build.conf.private

# revert changes to buildtime file
git checkout ts/${TS_VERSION}/thinstation.conf.buildtime

# copy the images to the respective TFTP directory
if [ -e "${TFTP_ROOT}" ]; then
  if [ ! -e "${TFTP_ROOT}/thinstation" ]; then
    mkdir "${TFTP_ROOT}/thinstation"
  fi
  cp ts/${TS_VERSION}/boot-images/pxe/initrd ${TFTP_ROOT}/thinstation/initrd-${VERSION}
  cp ts/${TS_VERSION}/boot-images/pxe/lib.squash ${TFTP_ROOT}/thinstation/lib.squash-${VERSION}
  cp ts/${TS_VERSION}/boot-images/pxe/vmlinuz ${TFTP_ROOT}/thinstation/vmlinuz-${VERSION}
  cp ts/${TS_VERSION}/boot-images/pkg-packages/*.pkg ${TFTP_ROOT}/thinstation/conf/pkg/
fi
